---
- name: azure devops
  hosts: localhost
  vars: 
   - repo_name: "test-ansible1"
   - project_name: "test"
   - org: selvanayaki849
  vars_prompt: 
  - name: "username" 
    prompt: "Enter your ADO username" 
    private: no 
  - name: "pat" 
    prompt: "Enter your ADO PAT" 
    private: yes
  tasks:
   - name: creating Azure devops repo 
     ansible.builtin.uri:
      url: "https://dev.azure.com/{{org}}/{{project_name}}/_apis/git/repositories?api-version=7.1-preview.1"
      user: "{{username}}"
      password: "{{pat}}"
      method: POST   
      headers:
       Content-Type: application/json     
      body_format: json
      body: 
       name: "{{repo_name}}"
      force_basic_auth: true
    
